sylius_grid:
    drivers:
        - doctrine/orm
    templates:
        action:
            default: "@SyliusUi/Grid/_default.html.twig"
            create: "@SyliusUi/Grid/Action/create.html.twig"
            delete: "@SyliusUi/Grid/Action/delete.html.twig"
            show: "@SyliusUi/Grid/Action/show.html.twig"
            update: "@SyliusUi/Grid/Action/update.html.twig"
            links: "@SyliusUi/Grid/Action/links.html.twig"
        bulk_action:
            delete: "@SyliusUi/Grid/BulkAction/delete.html.twig"
        filter:
            string: "@SyliusUi/Grid/Filter/string.html.twig"
            boolean: "@SyliusUi/Grid/Filter/boolean.html.twig"
            date: "@SyliusUi/Grid/Filter/date.html.twig"