sylius_resource:
    settings:
        paginate: 2
        limit: 2
        allowed_paginate: true
        default_page_size: 2
#    translation:
#        locale_provider: app.translation_locale_provider

#    resources:
#        app.avatar:
#            driver: doctrine/orm
#            classes:
#                model: AppBundle\Entity\Avatar
#                form: AppBundle\Form\Type\AvatarType