sylius_user:
    driver: doctrine/orm
    resources:
        admin:
            user:
                classes:
                    model: App\Entity\AdminUser
                    repository: App\Repository\AdminUserRepository
                    form: App\Form\Type\AdminUserType
#                    interface: App\Entity\UserInterface
                    controller: Sylius\Bundle\UserBundle\Controller\UserController
                    factory: Sylius\Component\Resource\Factory\Factory
                templates: admin/crud

        regular:
            user:
                classes:
                    model: App\Entity\User
                    repository: Sylius\Bundle\UserBundle\Doctrine\ORM\UserRepository
                    form: AppBundle\Form\Type\UserType
#                    interface: App\Entity\UserInterface
                    controller: Sylius\Bundle\UserBundle\Controller\UserController
                    factory: Sylius\Component\Resource\Factory\Factory
#                templates: 'SyliusUserBundle:User'

        oauth:
            user:
                classes:
                    model: Sylius\Component\User\Model\UserOAuth
                    interface: Sylius\Component\User\Model\UserOAuthInterface
                    controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                    factory: Sylius\Component\Resource\Factory\Factory
                    form: Sylius\Bundle\UserBundle\Form\Type\UserType
#                templates: 'SyliusUserBundle:User'