sylius_grid:
    grids:
        app_admin_user:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\AdminUser
            sorting:
                createdAt: desc
            limits: [2,4,6]

            fields:
                username:
                    type: string
                    label: sylius.ui.username
                    sortable: ~
                email:
                    type: string
                    label: sylius.ui.email
                    sortable: ~
                createdAt:
                    type: datetime
                    label: sylius.ui.registration_date
                    sortable: ~
                    options:
                        format: d-m-Y H:i
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
#            filters:
#                search:
#                    type: string
#                    label: sylius.ui.search
#                    options:
#                        fields: [email, username, name]
#                enabled:
#                    type: boolean
#                    label: sylius.ui.enabled
            actions:
                bulk:
                    delete:
                        type: delete
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete